// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0hoJf4WZug2sy-Q0a9IJ8Sr3twtg6mk',
    appId: '1:889763140910:android:973a383adf73ffe26a96bf',
    messagingSenderId: '889763140910',
    projectId: 'kilowatts-covianhive-22177295',
    databaseURL:
        'https://kilowatts-covianhive-22177295-default-rtdb.firebaseio.com',
    storageBucket: 'kilowatts-covianhive-22177295.firebasestorage.app',
  );
}
